# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2  # Wait for both Python 3.12 and 3.13 tests

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 60%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/test_*.py"
  - "scripts/**"
  - "htmlcov/**"

flags:
  unittests:
    paths:
      - custom_components/unraid_management_agent/
    carryforward: true

github_checks:
  annotations: true
