name: Validate with hassfest

permissions: {}

on:
  push:
    branches:
      - main
      - "enhancement/**"
      - "feature/**"
      - "fix/**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6
      - uses: "home-assistant/actions/hassfest@f6f29a7ee3fa0eccadf3620a7b9ee00ab54ec03b" # master
